// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQ7yWI-uG1Wg0kS3Ap0A9rfbFD8nCzBA',
    appId: '1:217116638618:web:e2a700cf18c0b18cbd8e23',
    messagingSenderId: '217116638618',
    projectId: 'merkar-app',
    authDomain: 'merkar-app.firebaseapp.com',
    databaseURL: 'https://merkar-app.firebaseio.com',
    storageBucket: 'merkar-app.appspot.com',
    measurementId: 'G-SMMW7K30ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGBgKPLBDW90iuv5qvJIazekyhadBL60M',
    appId: '1:217116638618:android:78aa1b2d40cfdcccbd8e23',
    messagingSenderId: '217116638618',
    projectId: 'merkar-app',
    databaseURL: 'https://merkar-app.firebaseio.com',
    storageBucket: 'merkar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-m4e_9G2mBPEBMP_QwnYvid9J0ht7G3Y',
    appId: '1:217116638618:ios:12f122c1acf1342ebd8e23',
    messagingSenderId: '217116638618',
    projectId: 'merkar-app',
    databaseURL: 'https://merkar-app.firebaseio.com',
    storageBucket: 'merkar-app.appspot.com',
    androidClientId: '217116638618-p3frqdckurr6uaj3godfv28q0n839oa4.apps.googleusercontent.com',
    iosClientId: '217116638618-r8i2f4qjo6068o10pbnre2tdqt8lciaq.apps.googleusercontent.com',
    iosBundleId: 'com.merkar.app',
  );
}
